### ISSUE TITLE
[Manage-HPBIOSPasswords] SetupSet not functioning correctly

### ISSUE THREAD

**Issue by MKeefeus** [ConfigJon/Firmware-Management#1]
Whenever I tried to use -SetupSet from Powershell directly, I would get the error ""When using the OldSetupPassword or SetupPassword parameters, one of the SetupChange or SetupClear parameters must also be specified"

As far as I can tell the error stems from lines 315-320
`if (($OldSetupPassword -or $SetupPassword) -and !($SetupChange -or $SetupClear))
{
	$ErrorMsg = "When using the OldSetupPassword or SetupPassword parameters, one of the SetupChange or SetupClear parameters must also be specified"
	Write-LogEntry -Value $ErrorMsg -Severity 3
	throw $ErrorMsg
}`

SetupSet requires the -SetupPassword parameter but then this code throws an error because neither $SetupChange or $SetupClear are true

**Comment by ConfigJon** [comment]
I updated the script and removed the SetupChange parameter completely. I updated the parameter validation section to reflect this change. It should work as you expect it to now.
