### ISSUE TITLE
ampersand

### ISSUE THREAD

**Issue by ShamblerDK** [ConfigJon/Firmware-Management#3]
When trying to run the PS scripts for both Lenovo and HP, I get the following error:

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

What am I doing wrong?

**Comment by ConfigJon** [comment]
I'm guessing this error had something to do with how the scripts were being called. When running the scripts from a PowerShell prompt, put a .\ in front of the script name.
.\Manage-LenovoBiosPasswords.ps1

When running the scripts from CMD, use a command like this: 
Powershell.exe -ExecutionPolicy Bypass -File Manage-LenovoBiosPasswords.ps1
