### ISSUE TITLE
How to read and set the hidden items in Lenovo BIOS?

### ISSUE THREAD

**Issue by crazyi** [ConfigJon/Firmware-Management#4]
As you known, Cfg lock is important in hackintosh, but it is hidden by Lenovo in its BIOS UI interface.
Is there any way to read and set the hidden items in Lenovo BIOS?

**Comment by ConfigJon** [comment]
The only settings I've been working with are the ones returned from the Lenovo_BiosSetting WMI class. If there is a setting that doesn't appear there, then Lenovo probably does not intend for it to be set programmatically.
