### ISSUE TITLE
Bios-settings wont save

### ISSUE THREAD

**Issue by eccoes** [ConfigJon/Firmware-Management#5]
BIOS-Settings wont save if you have a BIOS-password set.
To make sure the settings are saved you need to edit 

$SaveSettings.SaveBiosSettings() | Out-Null
To
($SaveSettings.SaveBiosSettings("$SupervisorPassword,ascii,us”)) | Out-Null

**Comment by ConfigJon** [comment]
Fixed this issue with the latest update to the script.
