### ISSUE TITLE
Apply a supervisor password when no password is set?

### ISSUE THREAD

**Issue by klluedtke** [ConfigJon/Firmware-Management#6]
If this works like the Lenovo Bios Config Tool you cant set a password if no password is set correct? You can only change an existing password.

**Comment by ConfigJon** [comment]
Lenovo does not allow setting a supervisor password when no password is currently set. However, there is a new System Deployment Boot Mode feature on some newer Lenovo models. Booting into this mode will allow for setting an initial supervisor. Currently my script does not support this mode, but it's something I want to look into in the future.

https://thinkdeploy.blogspot.com/2019/11/system-deployment-boot-mode.html
